### ISSUE TITLE
Markdown style bug causing ordered/unordered lists to behave the same

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#3039] opened 2022-04-27 14:27 UTC
## Describe the bug
Report from Project Builder: "There is a bug in the style for the markdown for lists. Both unordered and ordered behave the same way."

## To Reproduce
From @mcbouslog: 
FEM not expected https://frontend.preview.zooniverse.org/projects/markb-panoptes/digileap-testing/about/research?env=staging 
NB: based on this from the lab about editor - https://master.pfe-preview.zooniverse.org/lab/1952/about/research

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

## Expected behavior
expected (PFE) https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/digileap-testing/about/research?env=staging

## Screenshots
FEM (not expected): 
![Screen Shot 2022-04-27 at 9 25 09 AM](https://user-images.githubusercontent.com/25958358/165541207-c332b70f-f006-49cf-b968-a55c690a9cfb.png)

PFE (expected): 
![Screen Shot 2022-04-27 at 9 25 37 AM](https://user-images.githubusercontent.com/25958358/165541315-4c5f1489-39d5-47e3-8147-2b3ad8e2e7ee.png)

## Possibly related Markdown issues:
Received May 09 via Talk (FEM project 15969): "I have had varying degrees of difficulty creating spacing between lines. Sometimes adding an extra return between lines helps or adding three or more spaces at the end of a line. However, in the Field Guide text, I have been unable to add extra spaces between lines using markdown. I've tried backslashes, extra spaces at the end of lines, and extra space between lines, and none of these seem to work consistently."

Received May 10 via Talk (FEM project 15597): " I'm losing icons for topics in the Field Guide. They all appear when editing the guide, but when clicking on the Field Guide button during the transcription process, most are missing. When I go into the actual topic page, they are also missing." I checked the lab, and all the icons are appearing as they should on the Field Guide page. See screenshots below:

FG boxes as they currently appear on FEM project page:
![Screen Shot 2022-05-12 at 1 52 46 PM](https://user-images.githubusercontent.com/25958358/168147790-d033891a-1af6-42da-ac58-334de0d701c4.png)

FG icons as they appear in PFE lab:
![Screen Shot 2022-05-12 at 1 53 31 PM](https://user-images.githubusercontent.com/25958358/168147896-dc8802f7-abbf-4b67-b0db-84a5b7d9c4fa.png)

Received May 19 via email (FEM project `5481`):

>  I was trying to finalize my Field Guide this week, a lot of resizing of sample images of individual letters, and I just seem to be missing something in the markup. I can't seem to get the image samples to stay at a smaller size so they aren't so pixelated. I've tried multiple ways to format the image and hold it to 152x89 pixels (which is the native size), but the Field Guide keeps displaying the image at the larger size or not at all (as if the markup language is not understood. 
<img width="996" alt="Field Guide as Displayed on Zooniverse" src="https://user-images.githubusercontent.com/25958358/169319572-ad9b6337-81bb-41ff-b58e-07d849c39755.png">

**Comment by snblickhan** [comment] 2022-05-12 18:54
Note: added 2 possibly(?) related Markdown issues from FEM project team reports.

**Comment by snblickhan** [comment] 2022-05-19 14:29
Added 1 more Markdown issue from a team using FEM.

**Comment by goplayoutside3** [comment] 2022-05-24 17:10
I'm looking into the lists styling today.

In the future it will be most helpful if the reported markdown issues are documented in separate issues based on the unexpected behavior: 
1. lists styling 
2. creating space between lines 
3. icons in the field guide 
4. unable to resize images in the field

Regarding # 4, project 5481 field guide images have image urls incorrectly formatted. The markdown guide snapshot below shows how to resize field guide images. Project 5481's urls include `=MxN` instead of replacing `M` and `N` with numeric values, or the resize syntax is missing all together.
<img width="754" alt="Screen Shot 2022-05-24 at 12 00 28 PM" src="https://user-images.githubusercontent.com/23665803/170092946-d045c47e-0250-400c-ac8c-3fad5cebba83.png">

**Comment by goplayoutside3** [comment] 2022-05-24 23:00
The root of the ordered list problem lies in FEM's `remark` version. Given the following input
```jsx
Ordered list:
1. item one 
2. item two 
3. item three
```
remark version 11 processes it to:
```jsx
Ordered list:
1\ item one 
2\ item two 
3\ item three
```
and it's rendered as a paragraph.
 
We want the original input to be processed to:
```jsx
Ordered list:

1. item one 
2. item two 
3. item three
```
 
Upgrading to remark version 12 fixes this issue, but also has unintended consequences for using footnotes in markdown. I have a PR incoming that addressed both ordered lists and preserves footnote styling.

**Comment by snblickhan** [comment] 2022-05-25 08:32
> I'm looking into the lists styling today.
> 
> In the future it will be most helpful if the reported markdown issues are documented in separate issues based on the unexpected behavior:
> 
> 1. lists styling
> 2. creating space between lines
> 3. icons in the field guide
> 4. unable to resize images in the field guide
> 
> Regarding # 4, project 5481 field guide images have image urls incorrectly formatted. The markdown guide snapshot below shows how to resize field guide images. Project 5481's urls include `=MxN` instead of replacing `M` and `N` with numeric values, or the resize syntax is missing all together. <img alt="Screen Shot 2022-05-24 at 12 00 28 PM" width="754" src="https://user-images.githubusercontent.com/23665803/170092946-d045c47e-0250-400c-ac8c-3fad5cebba83.png">

Thanks, Delilah -- particularly for the note about preference for potentially related issues. I'll definitely open new issues for each in the future, rather than putting them together!

**Comment by goplayoutside3** [comment] 2022-06-10 16:06
Ordered/Unordered lists in markdown was solved, so I'm closing this issue.

Problems with icons in the field guide is a separate issue here: https://github.com/zooniverse/front-end-monorepo/issues/3295

@snblickhan if there's still problems with creating space in markdown, please open a separate issue with screenshots of the desired effect that can be replicated in PFE, but not FEM if possible. Thanks!

**Closed by goplayoutside3** 2022-06-10 16:06 UTC
Labels: bug
