### ISSUE TITLE
LCV bug with switching between annotation and zoom states

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#919] opened 2019-06-12 19:46 UTC
**Package** lib-classifier

**Feature or Issue Description**
From Talk

> after selection a possible transit on the light curve, click on the "Move Subject" button and move subject -> the light curve moves left and right; after that, it is impossible to remove previously light curve selection and deselect "Move Subject" button.

https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2108/1020600?comment=1684479

**To Dos**

- [ ] Example

**Comment by eatyourgreens** [comment] 2019-06-12 19:51
Could this be a duplicate of #849? Drawing/panning should be a toggle, not two separate check boxes.

**Comment by srallen** [comment] 2019-06-12 21:25
I think it might. I want to document separately at first since I'm not sure yet.

**Comment by srallen** [comment] 2019-06-26 14:19
I suspect that this is a design issue. I'm wondering if PFE allowed you to make marks while in 'panning' mode, so users expect that here.

**Comment by eatyourgreens** [comment] 2019-06-26 14:29
Any mouse, touch or pointer event on the SVG would draw a mark, so you can't pan and draw at the same time with a pointing device. However, PFE (and the new classifier) do allow you to pan and zoom with the keyboard while drawing.

**Closed** 2024-01-03 23:04 UTC
Labels: bug
