### ISSUE TITLE
TESS does not define `taskType` in the classification data

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/front-end-monorepo#1631] opened 2020-04-27 14:02 UTC
[ADR 25](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-25.md) outlines the structure for classifier 2.0 drawing tasks as having the `taskType: drawing` defined in the classification data.  TESS currently sets the `classifier_version: 2.0` flag in the metadata but does not include this `taskType` value.

This was originally found when the new subtask extractor was deployed to aggregation https://sentry.io/organizations/zooniverse-27/issues/1633260758/?project=1760084&query=is%3Aunresolved

A [temp fix](https://github.com/zooniverse/aggregation-for-caesar/pull/291) is currently live on aggregation to default this value when it is not given in the classification and the metadata shows `classifier_version: 2.0`

**Comment by srallen** [comment] 2020-04-27 16:36
@CKrawczyk I'm having a look at the TESS code:

Here is a sample annotation:
``` json
{
  "task": "T1",
  "value": [{
    "x": 15.240757807304064,
    "tool": 0,
    "width": 0.9274213184158011,
    "toolType": "graph2dRangeX",
    "zoomLevelOnCreation": 1
  }],
  "taskType": "dataVisAnnotation"
}
```

For clarification, the TESS task does provide a `taskType` value, but it is not drawing. Similarly, the tool type in the values array is `graph2dRangeX`. We created the new `dataVisAnnotation` task type (short for data visualization annotation) and the `graph2dRangeX` tool to indicate that this task and tool annotate real data on plots, so similar to the drawing tools, but distinct in case more functional divergence happens in the future.  I'm not sure if these data plot annotation tool types will ever have sub-task like the drawing tools do. (We unfortunately didn't document this as an ADR like the new transcription task... I can do this this week, but that was a documentation failure on our part).

For the purposes of aggregation though, the specific tool annotation for TESS is very similar to the column shape, close enough right now, that I think the same shape extractor can be used as has been happening?

**Comment by CKrawczyk** [comment] 2020-04-28 10:17
Thanks for the clarification.  I agree TESS will not have to worry about subtasks, the issue is the `shape_extractor` uses a `@subtask` decorator to add subtask support to any task using it.  I will just have to update that wrapper to look for more than just `drawing` tasks.

This is not an issue for the transcription tool as that uses its own custom extractor rather than the general shape extractor.

**Comment by CKrawczyk** [comment] 2020-04-28 10:50
I am working on a new PR to ensure this will pass through the `shape_extractor` without issue.
https://github.com/zooniverse/aggregation-for-caesar/pull/295

I will also point out that the exact error I was seeing in the sentry issue above was a `key not found` error indicating `taskType` was not in the annotation rather than it not being the value `drawing`.

**Comment by srallen** [comment] 2020-04-28 14:26
@CKrawczyk Ok, sounds good. Do you have a classification id for the annotation that was missing `taskType`. If there is a classification annotation from TESS missing this, then there still may be a bug on the front end somewhere. As far as I can tell as of now, annotations submit correctly with a `taskType`.

**Comment by srallen** [comment] 2020-04-28 16:04
The issue is on Caesar, so closing in favor of this new issue: https://github.com/zooniverse/caesar/issues/1120

**Closed by srallen** 2020-04-28 16:04 UTC
Labels: bug
