### ISSUE TITLE
[RFC] Classification metadata for feedback - TESS user weighting, multiple transits (feedback rules)

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#399] opened 2019-01-28 18:59 UTC
**Package**
lib-classifier

**Feature or Issue Description**
A TESS subject with simulated data may have 3 (or more?) transits defined in it's subject metadata feedback (see subject 28635005 for reference).
A user may identify none, all or some of the transits defined in the subject metadata feedback. 
What is then expected for calculating a user's weighting score?

For example, if they miss any transit should we record a general fail, the opposite where if they identify any then they have succeeded, a percentage of successfully identified or something different?

Currently the data provided in a classification's `metadata.feedback` is as follows:
```
{
  "T0": [
    {
      "failureEnabled": true,
      "hideSubjectViewer": false,
      "id": "5678",
      "strategy": "column",
      "successEnabled": true,
      "tolerance": "10",
      "x": "500",
      "width": "50",
      "failureMessage": "Nope =( 5678",
      "successMessage": "Nice! 5678",
      "success": false,
      "successfulClassifications": []
    },
    {
      "failureEnabled": true,
      "hideSubjectViewer": false,
      "id": "1234",
      "strategy": "column",
      "successEnabled": true,
      "tolerance": "10",
      "x": "50",
      "width": "60",
      "failureMessage": "=( Fail",
      "successMessage": "Success!",
      "success": false,
      "successfulClassifications": []
    }
  ]
}
```
Note the array of results for each feedback rule provided (this example came from a subject with two feedback rules).
I think what we're proposing here is an additional attribute somewhere that would signal an overall failure/success/percentage.
I'm not sure if that means changing `T0` to an object and adding a new property in addition to the current array, adding an attribute on the parent `feedback` property like `T0_success: 0.5` or something else?

**Comment by zwolf** [comment] 2019-01-28 21:55
Currently, when a user classifies a training subject with more than one `feedback_[x]_id` defined, it will show the success/fail message for each possible "feedback" (or transit, in TESS's case). This doesn't seem like optimal behavior, especially the way that the TESS training subject metadata is currently being uploaded. 

It seems like a single rule would be sufficient for however many transits there are, since the messages are being defined in the subject metadata (and even if they weren't, they'll likely be the same across subjects). Calculating a subject-wide success/failure and showing the message defined in the rule would allow Caesar to just pluck extract that single value, which it already knows how to do. It can then itself do the math to calculate how difficult it was, which Nora's user weight reducer requires.

**Comment by noraeisner** [comment] 2019-02-01 08:05
@mcbouslog - at the moment the user weighting, which is calculated offline, only considers whether they marked something or not. The current code doesn't take into consideration whether they marked it in the right place because the way that I have written that takes too long to run at the moment (I'll be working on changing this next). Would it be possible to include whether they marked the transits right or wrong in the outfile - that would definitely speed things up? In terms of the actual weighting: the weighting should increase with every transit that they mark correctly. However, seeing a third and fourth transit is much easier than seeing the first and second, so the weighting should increase the most for the first, a bit less for the second etc. until, say,  they mark 5 transits correctly after which point any more markings do not increase the up-weighting. The down-weighting due to missed transits would be similar. In other words, it would be great if the weighting could vary depending on how many transits they mark correctly if that's possible.

**Comment by srallen** [comment] 2019-02-13 21:56
I've confirmed with @noraeisner in the call today that the way we format the feedback in the classification metadata is what is needed. We do not need to add an overall success boolean/percentage.

I'll leave this PR open for now because we also discussed the UI and it sounds that a single message for success and failure is still preferred though?

**Comment by srallen** [comment] 2019-05-22 19:55
Closing since we have a distinct feedback UI issue.

**Closed by srallen** 2019-05-22 19:55 UTC
Labels: discussion
