### ISSUE TITLE
Classifier tutorial modal does not open when logged out

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5009] opened 2023-07-13 18:49 UTC
## Package
app-project
lib-classifier

## Describe the bug

Relates to https://github.com/zooniverse/front-end-monorepo/issues/5008

The tutorial modal should show when a logged out (anonymous user) views the classify page for any project. If a signed-in user is viewing the classifier and signs-out, the tutorial modal should open when the classifier refreshes.

## To Reproduce
1. While signed-out, go to any FEM project such as [PH TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess)
2. Go to the [classify](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235) page
3. The tutorial modal does not display

**Comment by eatyourgreens** [comment] 2023-07-13 20:44
I've got this fixed on a branch. Just figuring out how to mock PAnoptes so that the tests for an anonymous user also load a workflow tutorial.

Turns out this is caused by setting the key to null here, thus skipping the Panoptes API for anonymous users.
https://github.com/zooniverse/front-end-monorepo/blob/4e74f67e0d977ee1b18c89d7a0e94dcb25a2419c/packages/lib-classifier/src/hooks/useProjectPreferences.js#L51-L52

I should have tested that particular optimisation, because `useSWR` returns this when the cache key is null:
```js
{
  data: undefined,
  isLoading: false
}
```

**Closed** 2023-07-14 15:36 UTC
Labels: bug, degraded-ux
