### ISSUE TITLE
Classification model: add support for repeated tasks

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#538] opened 2019-03-12 14:23 UTC
https://github.com/zooniverse/front-end-monorepo/blob/7594f6b2c37db57380b1d552d5e7c6bc067287af/packages/lib-classifier/src/store/Classification.js#L35-L42

Panoptes allows tasks to be repeated more than once during a workflow eg. cataloguing a list of items by answering questions about each item. The resulting annotations array would be something like `[ T0, T1, T2, T1, T2…]` where T1 and T2 are the tasks that repeat.

At the moment, I think `annotations.set(taskKey)` will just overwrite any existing annotation because map keys are unique.

**Comment by srallen** [comment] 2019-11-15 11:54
I think this is a duplicate of #1226. Closing this since #1226 has more discussion on it.

**Closed by srallen** 2019-11-15 11:54 UTC
Labels: enhancement
