### ISSUE TITLE
Drawing component subtask pop-up doesn't close on touch devices

### ISSUE THREAD

**Issue by MaysaB** [zooniverse/front-end-monorepo#3550] opened 2022-08-17 17:26 UTC
## Package
lib-classifier

## Describe the bug

When drawing tool with sub-task is used on touch devices, user is unable to use the 'x' on top right hand corner or 'save and close' button the exit the modal. 

## Expected
User should be able to use the x and close buttons to exit the pop up - as shown on responsive dimensions.
Screenshot of expected outcome.

https://user-images.githubusercontent.com/49612167/185203050-46a0ec7e-fb1c-424b-9285-a7876a15bb67.mov

## Actual
User can only exit the pop-up by clicking outside of the pop-up.
Screenshot of actual outcome

https://user-images.githubusercontent.com/49612167/185202984-dc59c6da-88ba-4601-8cf1-734b4631e7f5.mov

## To Reproduce

1. Go to 'https://frontend.preview.zooniverse.org/projects/huhui/dental-disease-detection/classify/workflow/17233'
2. Click on image to create rectangle. Click rectangle to view pop-up.
3. Go to dev tools and change dimensions to iPad Air.
4. Attempt to exit out of pop up using the close buttons.

## Device information

 - macOS
 - Chrome, 104. Firefox, 103.

### Smartphone (please complete the following information):
 - iPhone 13 Pro, 15.6
 - Firefox. Safari.

## Additional context
1. Other buttons on the pop-up work fine.
2. Exists as of commit [56ad87d](https://github.com/zooniverse/front-end-monorepo/commit/56ad87d35b14ac36ea3ea8e6308c6c642687b77c)

**Comment by shaunanoordin** [comment] 2022-08-19 15:19
This is a duplicate of #3344 , so I'll close this issue. No worries though, this additional documentation is very useful for 3344, and the exercise in writing a very detailed issue is always good to have! 👍

**Closed by shaunanoordin** 2022-08-19 15:19 UTC
Labels: bug, ui
