### ISSUE TITLE
Move registration and sign forms

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#946] opened 2019-06-24 19:37 UTC
**Package** app-project, lib-react-components

**Feature or Issue Description**
Move the views for the modal and forms to the lib-react-components package maybe as part of the ZooHeader so they can be reused between apps.

**Comment by rogerhutchings** [comment] 2019-09-19 12:52
Duplicate of #871

**Closed by rogerhutchings** 2019-09-19 12:52 UTC
Labels: enhancement
