### ISSUE TITLE
CORS issue with certain TESS Subjects

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1845] opened 2020-10-07 21:25 UTC
## Server(?) Issue

Package: n/a - file server related, probably

Certain TESS Subjects (which consists of a JSON.txt file and an image file) will refuse to load on the `app-classifier`'s Light Curve Viewer subject viewer.

- Investigation indicates that for _certain_ Subjects, the JSON.txt file (which is hosted on `https://panoptes-uploads.zooniverse.org/`) returns a CORS error when a GET request is made.
  - Most other TESS Subjects' JSON.txt files seem to load OK, and the CORS error is consistent for the problematic Subjects. (i.e. this is easily replicable.)
- The response to the GET request, essentially, is missing `access-control-allow-methods: GET, PUT, POST` and `access-control-allow-origin: *` from its HTTP headers. This results in web browsers (tested on Chrome85) throwing a `Access to XMLHttpRequest at 'https://panoptes-uploads.zooniverse.org/production/subject_location/4105006f-5fff-48f6-9b23-3b7ce2fe066e.txt' from origin 'https://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` error.

### Original Report

Nora originally reported this on Slack [(link)](https://zooniverse.slack.com/archives/CANKLB50E/p1602091476282700) on 7 Oct. @eatyourgreens has indicated also seeing this problem before.

Original report:
> Hey, I don’t know whether this is related but I just went through a couple of classifications and I got a blank screen like this twice (spaced by ~10 classifications). When I then clicked done and talk I see the image displayed fine. I’ve tried to replicate it again but everything seems to be fine again. But in case that subject is related to the other problem, the subject ID is 50170586 (https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/subjects/50170586).

<img width="1373" alt="Screenshot 2020-10-07 at 18 46 54" src="https://user-images.githubusercontent.com/13952701/95386602-75b20280-08e7-11eb-82b1-04149c3b31ad.png">

_Image of the Subject 50170586 not loading on the Planet Hunters TESS website [(link)](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify)_

### Testing

While this issue can be replicated, it's might be difficult to do so, since I've **only been able to replicate the error in Chrome,** and not tools like Postman or cURL. 🤷‍♂️ 

**Baseline**

For our tests, we'll have two Subjects (they're on production), with the following information.

- 🔴 Subject 50170586, which has a JSON.txt file at https://panoptes-uploads.zooniverse.org/production/subject_location/4105006f-5fff-48f6-9b23-3b7ce2fe066e.txt
  - Attempting to fetch the file at 🔴 https://panoptes-uploads.zooniverse.org/production/subject_location/4105006f-5fff-48f6-9b23-3b7ce2fe066e.txt via Chrome will result in a CORS error ☠️ 
- 🔵 Subject 50179198, which has a JSON.txt file at https://panoptes-uploads.zooniverse.org/production/subject_location/e88f5a79-de9b-43e9-a002-c27646572245.txt
  - Attempting to fetch the file at 🔵 https://panoptes-uploads.zooniverse.org/production/subject_location/e88f5a79-de9b-43e9-a002-c27646572245.txt via Chrome will be OK. 👍 

**Testing on Chrome, Localhost**

Package: `lib-classifier`
Branch: `mobx-react-with-hack`

A recent `mobx-react-with-hack` branch allows us to specify which Subject to load via query parameters. This is the closest way we can replicate the error encountered by Nora on the live zooniverse.org website, since the error is Subject-specific but the non-hacked zooniverse.org code doesn't allow us to selectively choose Subjects.

**Test Case 1:** 🔴 Subject 50170586 was loaded via https://localhost:8080/?env=production&project=7929&workflow=11235&subject=50170586

<img width="1279" alt="Screen Shot 2020-10-07 at 22 03 41" src="https://user-images.githubusercontent.com/13952701/95387820-31bffd00-08e9-11eb-8f0b-61e414e392d4.png">

Observing the Network call to the JSON.txt file, we see the following header data in the response:

```
accept-ranges: bytes
content-length: 139562
content-type: text/plain
date: Wed, 07 Oct 2020 17:32:07 GMT
etag: "dfbdfbba40ccf498610c87f20fe0c1cc"
last-modified: Mon, 28 Sep 2020 06:38:28 GMT
server: AmazonS3
status: 200
x-amz-id-2: jJZjRszYIk6GCtjTXUWR7VbTZkFivfOV9NfqcWVjqOdhkkj5sqdeKO3spyzmIwF8s/ZkZFoeqJg=
x-amz-request-id: CB4F43329117ECC8
x-amz-version-id: s8YHSshrmBd_1tHshmyOAIpHAX7gwuQV
x-azure-ref: 0mPt9XwAAAADLBA/0TnUuTbtMnOLPcwMlTE9OMjFFREdFMDIxOAAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
x-cache: TCP_HIT
```

**Test Case 2:** 🔵 Subject 50179198 was loaded via https://localhost:8080/?env=production&project=7929&workflow=11235&subject=50179198

<img width="1280" alt="Screen Shot 2020-10-07 at 22 09 09" src="https://user-images.githubusercontent.com/13952701/95388217-c7f42300-08e9-11eb-836e-91ed0bd82568.png">

Observing the Network call to the JSON.txt file, we see the following header data in the response:

```
accept-ranges: bytes
access-control-allow-methods: GET, PUT, POST
access-control-allow-origin: *
access-control-max-age: 3000
content-length: 118688
content-type: text/plain
date: Wed, 07 Oct 2020 20:59:26 GMT
etag: "befc005a765b5a87470cace10626e496"
last-modified: Mon, 28 Sep 2020 08:11:46 GMT
server: AmazonS3
status: 304
vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
x-amz-id-2: fXH1PKEz6iczAk7QNQNkqIvxnTkX1lxgWEZWZ+7fompjUYvfQbOq2VYLCzByNlspZY4dyL2QGZs=
x-amz-request-id: 77DD8B55C875EB10
x-amz-version-id: ezyGdcpyX2radTo0GlH8UwyUmcRtctZp
x-azure-ref: 0Lix+XwAAAAAbyTse27pSS5THmq2fPDdaTE9OMjFFREdFMDIxMAAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
x-cache: TCP_HIT
```

Observations:
- 🔵 Subject 50179198's JSON.txt file had `access-control-allow-origin: *`, etc in the response header
- 🔴 Subject 50170586's JSON.txt file did NOT have the relevant entries in the response header
- Chrome's GET requests contained `Referrer Policy: strict-origin-when-cross-origin` in the headers. For example:

```
Request URL: https://panoptes-uploads.zooniverse.org/production/subject_location/e88f5a79-de9b-43e9-a002-c27646572245.txt
Request Method: GET
Status Code: 200  (from disk cache)
Remote Address: 13.107.246.10:443
Referrer Policy: strict-origin-when-cross-origin
```

**Testing on cURL**

**Test Case 3:** 🔴 Subject 50170586's JSON.txt was fetched via cURL.

Observation: `access-control-allow-origin: *` was not found in the header; this is expected, given the results of Test Case 1.

```
> curl -I https://panoptes-uploads.zooniverse.org/production/subject_location/4105006f-5fff-48f6-9b23-3b7ce2fe066e.txt

HTTP/1.1 200 OK
Content-Length: 139562
Content-Type: text/plain
Last-Modified: Mon, 28 Sep 2020 06:38:28 GMT
Accept-Ranges: bytes
ETag: "dfbdfbba40ccf498610c87f20fe0c1cc"
X-Cache: TCP_HIT
Server: AmazonS3
x-amz-id-2: RZ55QAj58KoQAz2C+KFNFxehLNULq0hKW2mMvUPeIsfnHpVr4dQA143nB2pqR+RYXf7c6uj2uBs=
x-amz-request-id: E0A5731FCBF4F38E
x-amz-version-id: s8YHSshrmBd_1tHshmyOAIpHAX7gwuQV
X-Azure-Ref: 0lS9+XwAAAADH/qE6qTwpTatYc1+5NuI/TE9OMjFFREdFMDIxNQAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
Date: Wed, 07 Oct 2020 21:13:56 GMT
```

**Test Case 4:** 🔵 Subject 50179198's JSON.txt was fetched via cURL.

Observation: `access-control-allow-origin: *` was NOT found in the header; which is UNEXPECTED, given the results of Test Case 2.

```
> curl -I https://panoptes-uploads.zooniverse.org/production/subject_location/e88f5a79-de9b-43e9-a002-c27646572245.txt

HTTP/1.1 200 OK
Content-Length: 118688
Content-Type: text/plain
Last-Modified: Mon, 28 Sep 2020 08:11:46 GMT
Accept-Ranges: bytes
ETag: "befc005a765b5a87470cace10626e496"
X-Cache: TCP_MISS
Server: AmazonS3
x-amz-id-2: c9PeeBoyWjxLg68fJaAeKtMyjLxP+tRKviYYKzxCfpooCZZzOOulhoTPYHDMHzsnLX0IvL5Aweg=
x-amz-request-id: EFE41A041C3A08E7
x-amz-version-id: ezyGdcpyX2radTo0GlH8UwyUmcRtctZp
X-Azure-Ref: 0NTB+XwAAAACEICxLemxQQY3AKRJCG0A1TE9OMjFFREdFMTUyMgAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
Date: Wed, 07 Oct 2020 21:16:37 GMT
```

**Testing on Postman**

The Postman HTTP-getting/posting/etc client returned the same results as Test 3 and Test 4 with cURL.

**Hypotheses?**

- Files hosted on `panoptes-uploads.zooniverse.org` are configured to return `access-control-allow-origin: *` in the header...
- ...in most cases, except for the problematic exceptions...
- ...and only if `Referrer Policy: strict-origin-when-cross-origin` is set in the request header?

### Status

Mysterious server-side problem remains mysterious.

- Error seems to affect a small number of Subjects (at least based on user complaints?), but the issue is not negligible.
- Finding out _why_ this is happening might be more important so we can understand the scope of the problem. (i.e. how many Subjects were affected, really?) 
- Medium impact... low urgency/priority? I think?

**Comment by srallen** [comment] 2020-10-07 22:18
This isn't unique to TESS, but rather any subject that we're using JSON data for. It's affecting the upcoming Stellar Sleuths project. @lcjohnso can fill in details about what he came across while working with that team to help them get subjects uploaded.

**Comment by camallen** [comment] 2020-10-08 09:08
CORS headers from s3 origins look just fine and are open for * domains.
```
$ curl -X OPTIONS -H "Access-Control-Request-Method: GET" -H "Origin: https://local.zooniverse.org" -I https://panoptes-uploads.zooniverse.org/production/subject_location/e88f5a79-de9b-43e9-a002-c27646572245.txt
HTTP/2 200 
vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
x-amz-id-2: L0qvItqF3KmYZGOaDVlECsmHu64EoRo+WWRkgvELIi1iLl+XgsW7b7cqSPxgCrZemTY6iCTFbKw=
x-amz-request-id: F5CFD61DF87753AD
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST
access-control-max-age: 3000
x-azure-ref: 0fdZ+XwAAAADp+WqQLi4TTZMx7UXkLNGjTE9OMjFFREdFMDIxMwAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
date: Thu, 08 Oct 2020 09:06:05 GMT
content-length: 0
```

However as this is impacting chrome only (we need to get some impacted versions) I think this is browser related, perhaps related to this change https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default ??

It may be the content types being different to the actual file contents, text vs json but 🤷 

I guess I'm going to have to get this working locally and debug it. FWIW as the issue is server side it should be reproducible from any branch.

**Comment by lcjohnso** [comment] 2020-10-08 15:38
As @srallen mentioned, I ran into the same CORS errors while debugging behavior related to Stellar Sleuths: two subjects would fail to load every time they were attempted.  Specifically, the error was `CORS header 'Access-Control-Allow-Origin' missing`. This was for subjects 49241177 and 49241180, members of test SubjectSet 87173 on Stellar Sleuths (Project 4878) when classified on Workflow 16135.  **NOTE**: the team has moved on in their internal testing, and the Subject+SubjectSet+Workflow combination is not accessible at this time for testing.

Adding to above discussion: this is **NOT** browser specific: I reproduced the same behavior in Firefox and Chrome at the time.

Furthermore: a user on the OceanEYEs project reported some similar sounding behavior on that normal PFE project (single image for classify viewer, question tasks) -- around 1-in-100 subject images would not load, and the image component would remain empty / white.  Although not confirmed, this could potentially be CORS related.  As I Slacked to @camallen -- I confirmed that this behavior was NOT due to bad data: I was able to confirm that the media files loaded in Talk and elsewhere, but that it seems to only happen in the classifier.  Relevant Slack thread is [here](https://zooniverse.slack.com/archives/C06LHUC6R/p1600317279086900) and OceanEYEs Talk thread is [here](https://www.zooniverse.org/projects/benjamin-dot-richards/oceaneyes/talk/2723/1624429?comment=2635935&page=1). I'll follow up on that thread to see if the user can inspect and investigate whether it is CORS related next time.

I wanted to draw attention to the OceanEYEs report because it broadens the possible scope of the issue: beyond txt+JSON based files to include JPGs, and beyond FEM to PFE.

**Comment by camallen** [comment] 2020-10-08 16:45
Thanks @lcjohnso this is very helpful. 

I've had a brief look into this and have some leads for manual debugging. Specifically how the browser will sometimes set the request headers to `sec-fetch-mode: no-cors` so no cors response headers and other times to ``sec-fetch-mode: cors` which comes with cors response headers. 

Next step is to debug this with a local version of PFE and / or the fe-project monorepo app and see if we can recreate the CORS failure and the images don't load in the classifier.

**Comment by srallen** [comment] 2020-10-16 18:41
More reports of CORS errors in #1853 affecting Stellar Sleuths subjects.

**Comment by srallen** [comment] 2020-10-19 20:18
It seems all the subjects in this subject set have CORS issues with the JSON location: https://www.zooniverse.org/lab/4878/subject-sets/88646

We can observe this error in the lab using the preview button. I see this error thrown in console, for example:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://panoptes-uploads.zooniverse.org/production/subject_location/e23b1cc6-547a-44ef-bb6f-22c04c2a39bd.txt with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by nciemniak** [comment] 2020-10-19 22:02
We may need to add HEAD to the allowed methods list in the S3 CORS configuration, as per suggestions [here in this SO post](https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header).

**Comment by srallen** [comment] 2020-10-20 17:29
The issue in #1856 is unrelated, but we have observed CORS errors as noted in #1853. There are some CORB errors in the lab with subject sets 88646 and 88658, but I'm guessing unrelated since the loading issue in the classifier ultimately was unrelated as noted.

**Comment by camallen** [comment] 2020-10-21 14:00
After having a think and look into this, it appears this may be related to the front door cache. Specifically if a request is issued by a non browser XHR request (python, curl, wget script etc) as these requests may not set the `Origin` request header. 

In turn if the request is missing the `Origin` header the S3 origin does not include the CORS headers** in the response. https://stackoverflow.com/questions/17570100/s3-not-returning-access-control-allow-origin-headers

As these domains have front doors caching / CDN in front of them, these non-cors responses would be cached in the frontdoor CDN. Any subsequent requests for the resource will thus be missing the CORS headers until the cache expires (up to 3 days https://docs.microsoft.com/en-us/azure/frontdoor/front-door-caching).

** CORS response headers from our S3 origin for static bucket
``` 
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST
access-control-max-age: 3000
```

Here i provide some example curl commands to simulate the flow i've described above and resulting in media resources being cached in front door without the required CORS headers for access via XHR in our UI codebase.
``` bash
# request to s3 origin without `Origin` header
# Note the missing CORS response headers, this request will be cached in frontdoor
$  curl -I https://panoptes-uploads.zooniverse.org/production/subject_location/5de07a53-d972-452b-aa37-f88596ff78ce.txt
HTTP/2 200 
content-length: 357683
content-type: text/plain
last-modified: Mon, 19 Oct 2020 19:35:05 GMT
accept-ranges: bytes
etag: "9918647a44f98a3d42e93ef4e4626f0a"
x-cache: TCP_MISS
server: AmazonS3
x-amz-id-2: r6cWiQQ3IRgrDh1O3V9iipKYNJGGi8fD7FzCcoQS+dQ1t90oF1hzameNjRj5VzSb0NY+fdu949M=
x-amz-request-id: FA4C2B486908C695
x-amz-version-id: Cv1sTZxsRr9O6LBumZm_DUUZEJotvvVN
x-azure-ref: 0+C+QXwAAAAAdDOa7sZ/GTYsnEN5lS/6/TE9OMjFFREdFMDIxNwAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
date: Wed, 21 Oct 2020 12:56:24 GMT

# Subsequent request is served by front door `x-cache: TCP_HIT` and does not have the CORS headers
$ curl -H 'Origin: https://www.zooniverse.org' -I https://panoptes-uploads.zooniverse.org/production/subject_location/5de07a53-d972-452b-aa37-f88596ff78ce.txt
HTTP/2 200 
content-length: 357683
content-type: text/plain
last-modified: Mon, 19 Oct 2020 19:35:05 GMT
accept-ranges: bytes
etag: "9918647a44f98a3d42e93ef4e4626f0a"
x-cache: TCP_HIT
server: AmazonS3
x-amz-id-2: r6cWiQQ3IRgrDh1O3V9iipKYNJGGi8fD7FzCcoQS+dQ1t90oF1hzameNjRj5VzSb0NY+fdu949M=
x-amz-request-id: FA4C2B486908C695
x-amz-version-id: Cv1sTZxsRr9O6LBumZm_DUUZEJotvvVN
x-azure-ref: 0XTCQXwAAAACCS9i2+tDxQqjrzCfJ7h2OTE9OMjFFREdFMDIyMQAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
date: Wed, 21 Oct 2020 12:58:04 GMT
```
Curl cmds to simulate the caching of resources with the CORS headers
``` bash
# with the `Origin` header (simulate a browser XHR request)
# S3 will respond with the CORS headers and front door will cache this response
$ curl -H 'Origin: https://www.zooniverse.org' -I https://panoptes-uploads.zooniverse.org/production/subject_location/a24e804c-9381-4e8f-8e23-1af011d1bffd.png
HTTP/2 200 
content-length: 76152
content-type: image/png
last-modified: Mon, 19 Oct 2020 19:35:05 GMT
accept-ranges: bytes
etag: "ca109368caa119586d605cdcf43511f6"
vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
x-cache: TCP_MISS
server: AmazonS3
x-amz-id-2: 9pqyGGPA28tLSXWoEKAVs++/p/GZdKydneYT12cIeZocV0bSQ6TIHB9XRL0oILwUiUbYIioGQ6E=
x-amz-request-id: 221699A720779A9B
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST
access-control-max-age: 3000
x-amz-version-id: fZ2vqi.4w567nLGoOxxq_bubRbyKjrzz
x-azure-ref: 0vTCQXwAAAAC+4phjWDIBR5SRW8/5mn9iTE9OMjFFREdFMDEwNgAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
date: Wed, 21 Oct 2020 12:59:41 GMT

# subsequent requests are served by front door with the CORS headers
$ curl -H 'Origin: https://www.zooniverse.org' -I https://panoptes-uploads.zooniverse.org/production/subject_location/a24e804c-9381-4e8f-8e23-1af011d1bffd.png
HTTP/2 200 
content-length: 76152
content-type: image/png
last-modified: Mon, 19 Oct 2020 19:35:05 GMT
accept-ranges: bytes
etag: "ca109368caa119586d605cdcf43511f6"
vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
x-cache: TCP_HIT
server: AmazonS3
x-amz-id-2: 9pqyGGPA28tLSXWoEKAVs++/p/GZdKydneYT12cIeZocV0bSQ6TIHB9XRL0oILwUiUbYIioGQ6E=
x-amz-request-id: 221699A720779A9B
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST
access-control-max-age: 3000
x-amz-version-id: fZ2vqi.4w567nLGoOxxq_bubRbyKjrzz
x-azure-ref: 0STKQXwAAAAAMnKsmpmn1SYk90pJw/h4fTE9OMjFFREdFMTUxNgAyMDgxYjI0OS00MTYyLTQ5YmUtOWMwYy1mMTk1YzBkODljODY=
date: Wed, 21 Oct 2020 13:06:17 GMT
```

**Comment by srallen** [comment] 2020-10-21 14:10
@camallen Would this affect Fetch API or is this specific XHR?

**Comment by camallen** [comment] 2020-10-21 14:18
> Would this affect Fetch API or is this specific XHR?

TBH i'm not sure about the fetch API, my understanding if the request originates in a browser context the Origin header will be set by the brower (value of the header will be the domain the request originates on)

![Uploading Screenshot 2020-10-21 at 15.17.51.png…]()

**Comment by srallen** [comment] 2020-10-21 14:19
The request always originates in the browser, so I'm a bit confused about how the above applies, but curious if switching over to Fetch API, which we should do anyway, would impact anything.

**Comment by camallen** [comment] 2020-10-21 14:22
> so I'm a bit confused about how the above applies

If a program (say a research team python script) requests the non-cached media URLs AND does not include the `Origin` header then we can re-create the missing CORS response headers that will lead to intermittent failures. 

I'm not sure how these requests are happening (problematic browser) but using the above request flows and linking into how the front door CDN works we can reproduce the missing headers and thus explain this behaviour in the browser.

**Comment by eatyourgreens** [comment] 2020-10-21 16:00
MDN has a useful list of which requests use CORS (both XHR and Fetch use it .)
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#What_requests_use_CORS

**Comment by camallen** [comment] 2020-10-21 16:42
Thanks @eatyourgreens 

https://stackoverflow.com/questions/42239643/when-do-browsers-send-the-origin-header-when-do-browsers-set-the-origin-to-null, this also seems a good explanation of when the browser will set the origin header.

We're using superagent, which i believe by default is XHR in browsers https://visionmedia.github.io/superagent/#browser-and-node-versions

So in theory any browser XHR get request will set the CORS context and send the origin (our .txt|json fetches match this). In contrast it appears the SVG `image` href element won't set the cors context (though it's not needed) and thus the origin won't be in the response headers (cached or otherwise)
```
# example SVG image element from https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/classify
<image height="971" width="875" xlink:href="https://panoptes-uploads.zooniverse.org/production/subject_location/26b81181-509f-4925-b303-a79fcc6cb56a.png"></image>
````

Is there a chance the existing code would mistakenly try to use the .txt file URL as the svg image element href? If that happened on occasion it could explain how the data file URL response ended up cached without the cors request headers and perhaps the intermittent nature of this issue...

**Comment by camallen** [comment] 2020-10-21 16:48
https://github.com/zooniverse/front-end-monorepo/blob/088d66fea63d2e3b1d8bb723e64c407086e0007b/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js#L135-L136

Perhaps this hard coded index lookup was the issue combined with the missing `txt/plain`mime type handling that was added in #1858 ?

That hard coding would depend on the order the locations were added to the subject and I assume most times it'll be correct but on occasion it might not be the image data, rather it could have been the json / txt data.

**Comment by srallen** [comment] 2020-10-21 17:15
This issue was first observed with TESS subjects, and there is no image subject viewer being used with it (the image location is ONLY used in Talk as a fallback to show something). I don't think we should get too focused on the Stellar Sleuth's reported case here.

**Comment by srallen** [comment] 2020-10-21 17:24
Have a look at the original report with a known subject on TESS with this issue: https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/subjects/50170586

Click to view the second location, which will throw the CORS error.

**Comment by camallen** [comment] 2020-10-22 15:04
Thanks those links and the consistent reproduction on the talk page was very helpful 👍 

I believe the issue is related to the comments i made in https://github.com/zooniverse/front-end-monorepo/issues/1845#issuecomment-713711580

Specifically it appears that the underlying issue is the browser is requests all the subject media resource URLs, however it does so without a 'cors' context for the request. Thus the request has no `Origin` header, S3 origin returns the response without CORS response headers and the CDN caches this response for future use (again no cors response headers)

Looking into the code in PFE, https://github.com/zooniverse/Panoptes-Front-End/blob/23b6fe9067bce11d1bd6d5b37e990907deff19ca/app/components/subject-viewer.cjsx#L278-L292

It appears that the talk subject viewer will preload the subject location URLs via a 'hidden div' for optimizing the frame viewer via cached image. Thus when it attempts to switch to the text frame, via the '2' index button below the png image, it then attempts to load the data via https://github.com/zooniverse/Panoptes-Front-End/blob/23b6fe9067bce11d1bd6d5b37e990907deff19ca/app/components/file-viewer/text-viewer.jsx#L34-L59

This loading fails as the CDN responds with the cached non cors header responses from the 'preloaded' requests. 

After some investigation it appears this behaviour is new since switching to Azure frontdoor vs AWS cloudfront. It appears that cloudfront was caching the responses based on the query strings. So I believe that this was working on the older cloudfront CDNs as the PFE `TextViewer` would issue a load request with the extra query strings via this fetch https://github.com/zooniverse/Panoptes-Front-End/blob/23b6fe9067bce11d1bd6d5b37e990907deff19ca/app/components/file-viewer/text-viewer.jsx#L43, whereas the preloaded images would not have this query string so the cached response was different and had the cors headers. See https://github.com/zooniverse/Panoptes-Front-End/pull/3689/commits/b95b1d3633540b35015d8e5ed6e824190a797c28

From here I think we can fix this by modifying the behaviour of the FrontDoor CDN, specifically we change it to match the cloudfront behaviour to cache based on query strings, https://docs.microsoft.com/en-us/azure/frontdoor/front-door-caching#query-string-behavior

Thoughts?

**Comment by camallen** [comment] 2020-10-22 16:30
I've modified the FrontDoor CDN config to cache based on request query strings. This appears to have fixed the 2nd subject viewer frame (txt/json data) after testing on https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/subjects/50170586

I'm closing for now as this CDN change appears to have fixed the underlying issue. Feel free to re-open / raise concerns if this still persists.

**Closed by camallen** 2020-10-22 16:30 UTC
Labels: bug
