### ISSUE TITLE
`required` flag isn't supported in any task types

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#688] opened 2019-04-10 13:24 UTC
**Package**

lib-classifier

**Comment by eatyourgreens** [comment] 2019-10-23 16:06
Tasks could have an `isComplete` view, which returns true if the task is required and has a valid annotaton, or just true otherwise. Views can then render differently depending on that flag.

Alternatively, annotations could have an `isComplete` view which returns true if the annotation value passes some validation rules for that type of annotation.

**Comment by srallen** [comment] 2019-10-23 16:15
I think it makes sense for annotation models to do this. For instance, when debugging the LCV task and annotations, there are specific rules the annotations should be validated against, like, is the annotation within the linear scale range of the x-axis. Certain task types can have specific rules defined similar to how feedback works?

**Comment by eatyourgreens** [comment] 2019-10-23 16:20
I'm thinking something like this in the task model (the logic might not be exactly correct):
```js
.views(self => ({
  get isComplete () {
    return (self.required && self.annotation.isValid) || true
  },
```
then the annotation model handles validation but `task.isComplete` tells us whether or not the task is finished and we can move on to the next task/step, without the annotation needing to know if the task is required.

**Comment by eatyourgreens** [comment] 2019-11-01 12:01
Looks like this is a duplicate of #305. That issue has no comments so I suggest closing it and keeping the discussion here.

**Comment by srallen** [comment] 2019-11-01 14:33
Not exactly. Checking for required is only one type of validation. For instance, each drawing tool has a more specific validations depending on the annotation type, but we sort of get that for free with MST models. However, we need to handle those MST errors of the annotation does't validation against the model. 

Other task types may have other kinds of specific validations.

**Comment by eatyourgreens** [comment] 2019-11-01 14:38
I think I see (I'm not sure) but drawing tools don't create annotations and I think validating marks is a slightly different problem.

I've started adding tests to that each task and annotation model does error with invalid data, but they're very basic at the moment.
https://github.com/zooniverse/front-end-monorepo/blob/1b9e3d4cd8398e4dc5f84889a628d757ff49544f/packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.spec.js#L15-L23

**Comment by srallen** [comment] 2019-11-15 12:13
Time estimate: 2 weeks

**Comment by eatyourgreens** [comment] 2019-11-15 12:23
See #1307. This should be done in the next couple of days, at least in the models.

**Comment by eatyourgreens** [comment] 2019-11-15 12:23
#1266 validates drawing tools.

**Closed** 2019-12-04 10:03 UTC
Labels: difficulty: medium, enhancement, has time estimate
