### ISSUE TITLE
[VSLCV] Nothing loads when all subjects classified

### ISSUE THREAD

**Issue by adamamiller** [zooniverse/front-end-monorepo#1853] opened 2020-10-16 14:48 UTC
**Package**

VSLCV

**Describe the bug**
I am not totally positive for what is going on, but right now, I cannot get anything to load for the VSLCV:

![image](https://user-images.githubusercontent.com/2434744/96272690-119cd780-0f94-11eb-8397-2f86aad01005.png)

I have encountered this a few times over the past week. Normally, I can just do a browser refresh and then a new subject loads. However, I'm finding right now that every refresh loads the same image as above. 

I am working with a test subject set of only 20 sources at the moment. I *think* I have classified 19 of the 20. My suspicion is that nothing is loading because I'm being served sources that I've already classified. It is also possible something entirely different is going on, because I have also seen a banner saying all subjects in the subject set have been classified (earlier in the week). 

Data does load in other browsers when I am not logged in.

**To Reproduce**
1. Log in to your Zooniverse account
2. Go to https://frontend.preview.zooniverse.org/projects/adamamiller/stellar-sleuths/classify
3. Classify most/nearly all of the 20 subject test set.
4. Data should not load eventually

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

**Expected behavior**
New data should load every time a classification is provided. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Firefox
 - Version: 81.0.1

**Additional context**
I do not think this is a critical issue to fix before running the beta test.

**Comment by adamamiller** [comment] 2020-10-16 15:02
**Update** - I just kept refreshing until data appeared. I finally got to the 1 unclassified subject, the data loaded, I classified it, and now I see this: 

![image](https://user-images.githubusercontent.com/2434744/96274902-ad2f4780-0f96-11eb-8783-68cd4d7fe133.png)

I suspect that my above theory is close to correct.

**Comment by adamamiller** [comment] 2020-10-16 15:03
That's the wrong screenshot above, I meant to show this: 
![image](https://user-images.githubusercontent.com/2434744/96274981-c9cb7f80-0f96-11eb-82e0-7bc49d13a885.png)

**Comment by srallen** [comment] 2020-10-16 15:11
@adamamiller when you get a failure on subject load, could you open up the javascript console in your browser (Found in Chrome by going to View > Developer > Javascript Console or right clicking anywhere on the screen and selecting inspect and then switching to the console tab). Let me know if you see any kind of error like this one:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://panoptes-uploads.zooniverse.org/production/subject_location/67b1c321-671f-42b6-83c4-936cc3df4867.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by srallen** [comment] 2020-10-16 16:02
Might be related to #1845

**Comment by adamamiller** [comment] 2020-10-16 16:56
@srallen Looks like I do get that error when nothing loads: 
![image](https://user-images.githubusercontent.com/2434744/96286797-8e38b180-0fa6-11eb-8020-67fca944013f.png)

Please let me know if there is anything else I can report back that would be helpful

**Comment by srallen** [comment] 2020-10-16 18:43
@adamamiller we've been tracking the CORS errors with subjects for a few days now in #1845. It's been happening more broadly and affecting image subjects on other projects as well. Thanks for the details. They may be helpful, but I can't promise we'll have a fix by Tuesday for it.

**Comment by adamamiller** [comment] 2020-10-16 22:20
@srallen No problem - I don't think this is a huge problem for the beta. And, as far as I can tell this is more an issue once all the subjects have been classified and I don't know that every beta tester will manage that

**Comment by camallen** [comment] 2020-10-21 13:45
@adamamiller I'm looking into this issue and have a couple of questions:
+ Do you use the python cli or python client to you uploading subject data to the API and cloud store? 
    + If neither what do you use?
+ After uploading the subject resources do you access the linked subject media location URLs** outside of a browser context, i.e. via python or other programmatic way (curl, wget etc)? 

** E.g. https://panoptes-uploads.zooniverse.org/production/subject_location/5de07a53-d972-452b-aa37-f88596ff78ce.txt

**Comment by adamamiller** [comment] 2020-10-21 14:33
> @adamamiller I'm looking into this issue and have a couple of questions:
> 
>     * Do you use the python cli or python client to you uploading subject data to the API and cloud store?
>       
>       * If neither what do you use?
> 
>     * After uploading the subject resources do you access the linked subject media location URLs** outside of a browser context, i.e. via python or other programmatic way (curl, wget etc)?
> 
> 
> ** E.g. https://panoptes-uploads.zooniverse.org/production/subject_location/5de07a53-d972-452b-aa37-f88596ff78ce.txt

@mcoughlin - Do you have the answers to these questions?

**Comment by mcoughlin** [comment] 2020-10-21 15:54
We use the python client (I think that is what panoptes is...):
https://github.com/mcoughlin/ztfperiodic/blob/master/ztfperiodic/zooniverse.py#L104

Not so far, we just access the labels:
https://github.com/mcoughlin/ztfperiodic/blob/master/ztfperiodic/zooniverse.py#L285

**Comment by camallen** [comment] 2020-10-21 16:17
Yes the Zooniverse API is the panoptes codebase (https://github.com/zooniverse/panoptes)

Thanks @mcoughlin for the detailed links, it's appreciated. Tracing the code it looks like you fetch the classification data and store the fetched batch in a hdf file for reuse. No programmatic access to the underlying uploaded subject media URLs.

**Comment by camallen** [comment] 2020-10-22 16:35
I believe this was related to the same underlying cause as outlined in #1845. Specifically https://github.com/zooniverse/front-end-monorepo/issues/1845#issuecomment-714558029

Those changes combined with #1858 should fix the issue for now, however I'm not 100% convinced we can't reproduce this in future as I can still see a request flow that will trigger this error (no cors header responses on the CDN cached resource). 

That said I think we're good to close this issue. Feel free to re-open / raise any issues if the behaviour is ongoing.

**Closed by camallen** 2020-10-22 16:35 UTC
Labels: bug
