### ISSUE TITLE
Errors don't make it to Sentry on apps

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1451] opened 2020-01-28 15:43 UTC
**Package** app-project, lib-classifier

**Is your feature request related to a problem? Please describe.**
We need to have working error log reporting to be able to more readily debug issues. A test page is setup to try submitting logs to Sentry, but it doesn't: https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/logger?env=staging

Sentry is configured in #962 and middleware added to the project stores in #1073. We know there's an issue with source maps in #1438 for the classifier too.

A sample project setup for sentry for comparison: https://github.com/zeit/next.js/blob/canary/examples/with-sentry

**Comment by zwolf** [comment] 2020-01-28 16:41
When I ran into this on tove, it turned out that I was rescuing from errors to render them before the middleware was able to grab and send them. Ended up overriding a lib method to manually catch those particular errors and send them to sentry before calling `super`: https://github.com/zooniverse/tove/blob/master/app/controllers/concerns/error_extender.rb#L23-L27

Make sure that you can manually send (via console or calling their client directly on your test page), then that you're not prematurely rescuing the errors you want to send.

**Comment by eatyourgreens** [comment] 2020-01-28 17:08
The Sentry logger checks for an environment variable so maybe that isn't set properly?
https://github.com/zooniverse/front-end-monorepo/blob/41dcdc82db2a43beeac2ab25c2dd4fdd15545daf/packages/app-project/src/helpers/logger/logNodeError.js#L3-L11

**Comment by camallen** [comment] 2020-01-28 17:12
I checked and that env var was available in the node env on the server, worth double checking though.

**Comment by eatyourgreens** [comment] 2020-01-28 17:29
That env var isn’t set in the browser, though, for the button on the test page.

**Comment by eatyourgreens** [comment] 2020-01-28 18:12
Oh, I was looking at the wrong handler. #1073 added a client-side error handler?

**Comment by eatyourgreens** [comment] 2020-01-28 18:21
Maybe I’m missing something but client errors are being handled by the same function as server errors, which would explain why the test page doesn’t work.

**Comment by camallen** [comment] 2020-01-28 18:41
> Maybe I’m missing something but client errors are being handled by the same function as server errors, which would explain why the test page doesn’t work.

That was my interpretation after reading the example project, i think this needs to be tested manually to simulate the message payload makes it to sentry, normally error trackers have a way to test this functionality.

**Comment by eatyourgreens** [comment] 2020-01-29 09:22
It's unclear from #1073 whether that test page is intended to test client or server errors. Running the project app locally, with a DSN take from the k8s setup files:
```
SENTRY_DSN=https://2a50683835694829b4bc3cccc9adcc1b@sentry.io/1492691 yarn dev
```
I can confirm that `dsn` is undefined inside `logNodeError` for client errors, which explains why client-side logging from the `/logger` page doesn't work when you press the 'Throw Error!' button.

If that page is intended to test server errors, then either throw a test error during page rendering, or have the 'Throw Error!' button initiate a request that throws an error on the server.

**Comment by eatyourgreens** [comment] 2020-01-29 12:11
I've been testing with a local branch modified to error on `project.fetch()` and those errors aren't being caught anywhere. I'll push a branch with a catch block that logs those errors to Sentry.

**Comment by eatyourgreens** [comment] 2020-01-29 12:14
See #1453 for server-side logging to Sentry.

**Comment by srallen** [comment] 2020-01-29 15:13
Yes, it's unclear what I was attempting to do with that test page. I was trying to get client side error logging to work so help try to resolve #1267 because I never could replicate it. We do need server side logging to work as well, though.

**Comment by eatyourgreens** [comment] 2020-01-29 15:54
I think the only thing that's missing for client error logging is to define the Sentry DSN in the client code.

**Comment by eatyourgreens** [comment] 2020-01-30 10:28
Does anyone know why the project app is set up to log Node errors with `@sentry/browser` and not `@sentry/node`?

**Comment by eatyourgreens** [comment] 2020-01-30 11:20
Running through this this morning in a local copy of the project app:
- Sentry is initialised in Node, using `@sentry/browser` but I think it should use `@sentry/node`.
- Sentry in Node picks up the DSN from `SENTRY_DSN`.
- `Sentry.init()` is never run in the browser (this is where `@sentry/browser` should be used.
- the DSN is undefined in the browser.

**Comment by eatyourgreens** [comment] 2020-01-30 15:25
I've just updated #1453 to add `SENTRY_DSN` to the browser environment. I _think_ this issue is fixed now.

**Comment by eatyourgreens** [comment] 2020-02-02 17:54
Re-opening this because Sentry logging isn't enabled in production.

Looking through the Jenkinsfile, I think `yarn build` is being run before `SENTRY_DSN` has been set, so the NextJS apps are bing built without logging in production.

Locally, I've been testing with 
```
SENTRY_DSN=https://2a50683835694829b4bc3cccc9adcc1b@sentry.io/1492691 yarn build && yarn start
```

I think our production setup is more like
```
yarn build
SENTRY_DSN=https://2a50683835694829b4bc3cccc9adcc1b@sentry.io/1492691 yarn start

**Comment by eatyourgreens** [comment] 2020-02-03 10:05
I've run this locally now, with a bunch of logging added:
```
yarn build
SENTRY_DSN=https://2a50683835694829b4bc3cccc9adcc1b@sentry.io/1492691 yarn start
```

I see `SENTRY_DSN ` as undefined in both Node and the browser. If that environment variable is not set during the build, then Sentry logging is not enabled.

Looking through the Docker and Jenkins setups, here is the Jenkins step that runs `yarn build` for the project app, then pushes the resulting image so that it can be deployed to Kubernetes. The k8s deploy runs `yarn start` and `SENTRY_DSN` is set in the k8s environment.
https://github.com/zooniverse/front-end-monorepo/blob/ac6edb04cdc4e5ae8afcd960e0e95ca8cfb96fce/Jenkinsfile#L63-L70

**Comment by eatyourgreens** [comment] 2020-02-03 10:11
My recommendation, I think, would be that the kubernetes setup for each of the NextJS apps should pull down the base monorepo docker image and run `yarn build && yarn start` in the appropriate directory/workspace.

**Comment by camallen** [comment] 2020-02-04 09:44
I think this explains a lot - https://nextjs.org/docs/api-reference/next.config.js/introduction
> next.config.js is a regular Node.js module, not a JSON file. It gets used by the Next.js server and build phases, and it's not included in the browser build.

It looks like the SSR bundles should be getting the ENV vars interpolated into the code via [dotenv-webpack](https://www.npmjs.com/package/dotenv-webpack#properties) via `systemvars` directive.
- https://github.com/zooniverse/front-end-monorepo/blob/309867fa5097e103778509003f7d27b69291376e/packages/app-project/next.config.js#L39

https://nextjs.org/docs/api-reference/next.config.js/environment-variables
> To add environment variables to the JavaScript bundle, open next.config.js and add the env config:
So our client bundles won't be getting the system vars as they aren't available at build time, right? 
Specifically, https://github.com/zooniverse/front-end-monorepo/blob/481e121773d868065e9de328ee0b853e09e2a929/packages/app-project/next.config.js#L17

This is confusing - https://zeit.co/docs/v2/build-step#using-environment-variables-and-secrets

I think we have to ensure that the CI tooling builds with the non-private secrets and server side can inherit the variables from the system vars as defined by K8s env.

**Comment by eatyourgreens** [comment] 2020-02-04 09:50
>So our client bundles won't be getting the system vars as they aren't available at build time, right?
Specifically,

Webpack runs during `yarn build`, yes, and generates the client js files.

**Comment by eatyourgreens** [comment] 2020-02-04 09:51
>I think we have to ensure that the CI tooling builds with the non-private secrets and server side can inherit the variables from the system vars as defined by K8s env.

This is only useful if kubernetes runs `yarn build` before it starts each app.

**Comment by camallen** [comment] 2020-02-04 10:00
> > So our client bundles won't be getting the system vars as they aren't available at build time, right?
> > Specifically,
> 
> Webpack runs during `yarn build`, yes, and generates the client js files.

So the non-secret env vars need to be available in the CI system to be available for the build step.

> > I think we have to ensure that the CI tooling builds with the non-private secrets and server side can inherit the variables from the system vars as defined by K8s env.
> 
> This is only useful if kubernetes runs `yarn build` before it starts each app.

Normally we do not building our app on boot as this increases the app start up time and thus one can have unavailable services (caesar suffers from this). That said we can use K8s to detect when the app is ready during deployment e.g. using `readinessProbe` https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

For client side (non-secret) variables, we can look at having them available via the CI tool (Jenkins) and thus they would make it into the client side bundles.

**Comment by eatyourgreens** [comment] 2020-02-04 10:03
>So the non-secret env vars need to be available in the CI system to be available for the build step.

Yep. If `SENTRY_DSN` was defined during the Jenkins build, then Sentry logging would be enabled.

**Comment by camallen** [comment] 2020-02-04 10:05
So i think we can do this via the jenkins build scripts - https://jenkins.io/doc/pipeline/tour/environment/

**Comment by eatyourgreens** [comment] 2020-02-04 10:09
Looking at the Jenkinsfile, I don't see any of the environment vars being set. Are all of these falling back to default values during the build stage? Also, I'm not sure if the secret new relic key will even be used.
https://github.com/zooniverse/front-end-monorepo/blob/bb1fc3dd88046dd007262ef2dcd8797fd2bc748a/kubernetes/deployment-production.tmpl#L36-L49

**Comment by eatyourgreens** [comment] 2020-02-04 14:20
>So i think we can do this via the jenkins build scripts -

Done, in #1480.

**Comment by camallen** [comment] 2020-02-04 14:45
Marvellous - we could add credentials to jenkins to keep them more isolated from code changes, https://jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials

**Closed** 2020-02-04 14:47 UTC
Labels: bug, dx, ops, performance
