### ISSUE TITLE
Task Area rendering with previous Classification

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1407] opened 2020-01-13 18:09 UTC
## Classification & UI Bug

Package: `lib-classifier`

On a project featuring a workflow with a single simple yes/no question, the Task Area of the Classifier UI _visually retains_ the yes/no answer of the previous Classification.

Tested on macOS 10 + Chrome 79

### Details

In this example, I'm using the Classifier to view a sample project (http://localhost:8080/?env=staging&project=1898) with only one yes/no question.

<img width="1280" alt="Screen Shot 2020-01-13 at 17 33 03" src="https://user-images.githubusercontent.com/13952701/72279328-d00a8500-362d-11ea-9cf6-adedc16c0fcc.png">

First, I receive the 1st Subject and select the "No" answer. I then click Submit.

<img width="1280" alt="Screen Shot 2020-01-13 at 17 33 22" src="https://user-images.githubusercontent.com/13952701/72279345-d698fc80-362d-11ea-9486-aba26fd08f19.png">

The 1st Classification is submitted and the 2nd Subject is loaded. Viewing the Network console, we note that the Classification is submitted with the correct values.

In the UI though, we see the first problem: the 'no' answer has already been selected, despite me not taking any further action after clicking the Submit button.

**Sub-Issue 1: UI doesn't reset between Subjects**

- Expected: when loading a new Subject, the task area's questions/answers should be reset. (i.e. neither 'yes' nor 'no' should be selected as an answer on the UI.)
- Actual: when loading a new Subject, the previous answer in the task area persists.

Without touching the yes/no answers, I now click the Submit button again.

<img width="1280" alt="Screen Shot 2020-01-13 at 17 33 45" src="https://user-images.githubusercontent.com/13952701/72279367-def13780-362d-11ea-9a4f-e8e6a452c473.png">

The 2nd Classification is submitted and the 3rd Subject is loaded. Viewing the Network console, we note that the Classification is submitted with **incorrect values.** Specifically, the UI says 'no' was selected (expected annotation value: 1), but the Classification says the user didn't choose any answer (actual annotation value: null)

**Sub-Issue 2: when UI doesn't reset, Classification sent doesn't reflect answers shown in UI**

- Expected: when the UI shows a yes/no answer being selected, that answer should be reflected in the Classification submitted to the API
- Actual: if the user doesn't interact with the UI, despite the UI showing a yes/no answer being selected, the Classification submitted to the API is blank

### Status

⚠️ This is a serious UI bug that can affect scientific classifications.

**Comment by shaunanoordin** [comment] 2020-01-13 18:19
I first discovered this issue when testing PR #1403, though later examination indicated that the problem was already extant in `master` (247ae16). 

According to @eatyourgreens (see [comment](https://github.com/zooniverse/front-end-monorepo/pull/1403#issuecomment-573782322)) , this problem should have been taken care off in  #1339.

> My fix for this, in #1339 by the way, had been to hold off classifying until onSubjectReady. Previously, it happened on classificationComplete, which fires while the previous classification is active.

Perhaps the Classifications ARE being reset onSubjectReady, because the 2nd Classification I submit to the API ARE blank. (value: null, despite the 'No' being selected in the UI.)

So this is likely UI related... somehow, the `SingleChoiceTask` isn't re-rendering (and therefore resetting) between new Subject loads. _(Maybe because for my example project, there's only one Task in the Workflow?)_ 🤔

**Comment by shaunanoordin** [comment] 2020-01-13 18:23
This "UI remembers answers for previous Task" problem does NOT happen on projects with multiple Tasks in a workflow. For example, http://localhost:8080/?env=staging&project=1895 has a workflow with a Drawing Task, then a simple Yes/No single answer Task.

With THIS project/workflow, the Yes/No answers do NOT persist between Subjects.

**Comment by eatyourgreens** [comment] 2020-01-13 18:53
The only difference I can think of is that maybe, with one task, the task component mounts once and doesn’t unmount.

**Comment by srallen** [comment] 2020-01-13 19:10
The task area is connected to the stores and would be rendering what is in the store, so I have my doubts that this is just a UI problem. The problem is likely in the workflow steps store.

**Comment by srallen** [comment] 2020-01-13 20:56
What I've found investigating this is that the `SingleChoiceTask` react component is using local component state to actually determine what to render:

https://github.com/zooniverse/front-end-monorepo/blob/247ae16ab7f31bf75b002a8e0b209fcf093a2b30/packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js#L37

This state is not reset in a single task workflow. It's confusing that we're tracking the value of the annotations in two places which are out of sync, so I experimented with removing this and discovered that the local component state was covering up a bigger problem with the task component not receiving updated props from its connection to the MST stores. The MST classification annotation is being updated if you use MST devtools to investigate, however, the way that the Task is connected, the value being connected is a cached computed view. Even with removing the getter, the Task component still isn't getting the updated value so I think there's an issue with how the stores are constructed since this should be a straight forward observation being made by the observer component and the data _is_ being updated. 

Going down the tree is very confusing now. Basically there area three derived views being used to return the actual annotation value now and there I think lies the issue. I think the intention of the derived view functions, whether they're cached or not, is meant to be derived data from its own store. Unfortunately, I do not see any easy fix to the observer problem without reverting much of what was refactored in #1212.

The other option is to manage the local component state, but this does not seem a like a good robust fix since it's covering an underlying issue.

@eatyourgreens any ideas?

**Comment by eatyourgreens** [comment] 2020-01-13 21:35
`annotation` should be passed down as an additional prop to tasks. See #1239. `task.annotation` was a mistake, in retrospect, since it couples each task directly to the classification.

**Comment by eatyourgreens** [comment] 2020-01-14 09:18
>I think the intention of the derived view functions, whether they're cached or not, is meant to be derived data from its own store.

That's not the bug. MST is absolutely fine with a derived value being a reference to a value from another store. Whether or not you should strongly couple two stores like this is a different question, however. I'm now of the opinion that you should not (see #1239.)

The bug was a combination of two things.

- `task` wasn't being observed for changes inside `tasks.map()`.
- `useState` is only called once, when a functional component mounts. If the default value is passed in as a prop, then only that very first value is used. Subsequent changes to the prop are ignored by React. This is by design because, as you point out, a component shouldn't be rendering from both prop and state changes at the same time.

**Comment by eatyourgreens** [comment] 2020-01-14 09:20
Fixed by #1409.

**Comment by shaunanoordin** [comment] 2020-01-14 16:17
## Investigation Update

The initial report for this UI issue focused on 1. workflows with '1x single choice answer task', and 2. persistent answers in the _Task Area._ These problems are handily solved by PR #1409 👍 

However, a follow up investigation revealed that a scenario was missed: _workflows with 1x drawing tasks_

### Details

In this example, I'm using the Classifier to view a sample project (http://localhost:8080/?env=staging&project=1895) with only 1x drawing task. (A Point tool)

![Screen Shot 2020-01-14 at 15 55 53](https://user-images.githubusercontent.com/13952701/72360548-fab91400-36e7-11ea-98a9-ffa976cb2182.png)

I receive the 1st Subject, and proceed to make 3x Point marks on the Elephant.

Note that there are 3x Point marks on the _Subject Viewer,_ and the _Task Area_ also indicates that 3x Points were drawn.

I now click Submit.

![Screen Shot 2020-01-14 at 15 56 05](https://user-images.githubusercontent.com/13952701/72360639-20deb400-36e8-11ea-8d01-592551563e54.png)

When the 2nd Subject loads, I still see the 3x Point marks on the _Subject Viewer._ These 3x Point marks persisted from the Classifications from the previous Subject.

The _Task Area,_ however, correctly shows that the number of marks in the Classification is currently 0.

**Follow up:**

- If I immediately click Submit, the Classification will be sent to the API with 0 annotations. (This is correct, because I haven't added any marks for the 2nd Subject)
- If I instead try to add a new Point mark, the previous 3x Point marks will disappear, and my new Point mark will appear.
- If I instead try to click on/interact with one of the previous 3x Point marks, the whole webpage will crash to a white page, with error message: `Uncaught Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'Point', Path upon death: '/workflowSteps/steps/S0/tasks/0/tools/0/marks/ck5e276p100013h5w9w6dnkqy', Subpath: 'id', Action: ''). Either detach nodes first, or don't use objects after removing / replacing them in the tree.` 

### Status

⚠️ It's still a serious UI bug. 🐛 

For the moment, I'm classifying this update (i.e. "btw workflows with 1x Drawing Task also have persistent answers") as an extension of the problem originally described in this issue.

However, I'm open to any argument that this should be _its own separate issue._ After all, we already have PR #1409 which solves the initial reported issue (for 'workflows with 1x single choice answer tasks'), and that PR alone made a significant amount of changes to the Task components.

I'm not sure if we should overload that fix with changes to the Subject Viewer as well. 🤷‍♂

**Comment by shaunanoordin** [comment] 2020-01-14 17:10
Based on discussions in #1409, the issue of _"Subject Area is rendering with previous Classification's marks"_ will be spun off as its own issue, to be investigated separately 👌

**Closed** 2020-01-15 12:57 UTC
Labels: bug
