### ISSUE TITLE
YourStats store does not update when going from one FEM project to another FEM project 

### ISSUE THREAD

**Issue by yuenmichelle1** [zooniverse/front-end-monorepo#5964] opened 2024-03-14 15:39 UTC
## Package
_Choose from the list:_
- [x] app-project

## Describe the bug
YourStats store does not update when user moves from one FEM project to another. 

## To Reproduce
1. Go to an FEM project (preferably one where you have classifications on) 
2. Update url to go to another FEM project. 
3. Scroll down to 'Your __FEM_PROJECT_NAME_ Statistics' 
4. Note that your statistics is the same as the same as step (1)

I attached screen recording with the steps to reproduce; 

## Screenshots

https://github.com/zooniverse/front-end-monorepo/assets/30220346/0ee361ca-892d-40e8-9af1-121c0b76e9fe

Explanation of the video: 
- Went to an FEM project (in this case People's Contest Digital Archive) [that week I did 1 classification that day and 4 in total for that project)
- Updated the url to go to Gravity Spy 
- Note that the 'Your Gravity Spy Statistics' SHOULD be 4 classifications that dat and 145 classifications total 
      -  BUT is showing the same statistics as that of People's Contest Digital Archive (1 classification that day and 4 total)

## Expected behavior
As I switch from one FEM project to another, YourStats store updates to reflect the project change. 

### Desktop (please complete the following information):
 - OS: [e.g. Windows 10]

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone]
 - OS:
 - Browser:
 - Versio:

**Comment by eatyourgreens** [comment] 2024-03-14 15:55
I think this is a duplicate of https://github.com/zooniverse/front-end-monorepo/issues/5134.

**Closed** 2024-12-06 19:24 UTC
Labels: bug
