### ISSUE TITLE
Survey task workflow errors when loading subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6368] opened 2024-10-09 20:32 UTC
## Package
lib-classifier

## Describe the bug
This survey task workflow errors and doesn't show subjects. 

https://www.zooniverse.org/projects/abbsta/south-coast-threatened-fauna-recovery-project/classify/workflow/21967

<img width=400 alt="Screenshot of the classifier showing 'Something went wrong' instead of a subject." src="https://github.com/user-attachments/assets/72dc9605-65e8-45be-920f-0d60c31f9865">

Screen recording on iOS:

https://github.com/user-attachments/assets/e7bcd2f5-b53e-4b66-9d8f-ecc1a14f16c2

## Expected behavior
The workflow is almost complete but should still show finished subjects. 

## Additional context

https://www.zooniverse.org/talk/2354/3326062?comment=5692998

**Comment by eatyourgreens** [comment] 2024-10-10 14:28
There's one remaining unclassified subject with a corrupted image upload, which errors when the image is loaded in the browser.

**Comment by shaunanoordin** [comment] 2024-10-10 15:40
As noted, the error appears to be caused by the FEM Classifier (`lib-classifier`) being unable to handle broken image files.

Sequence of events leading to error are:
1. workflow is (mostly?) complete so serves the same set of "unclassified" subjects. **All these subjects contain broken image files.**
2. Classifier loads subject, then attempts to load media files.
3. media file fails to load (i.e. broken image file), and Classifier doesn't have special handlers for this, so returns the generic "Something went wrong" error message.

As of 10 Oct 2024, the following 6 Subjects (all problem subjects) are being returned by `/queued`: 98392540, 98392819, 98393284, 98393285, 98393286, 98393287 

<details>
<summary>Example of a problem: subject 98393286</summary>

This subject contains 3 image files, all of which are broken:

- https://panoptes-uploads.zooniverse.org/subject_location/db0a4a7b-bab2-4351-b46e-fdfa38822d6f.jpeg
- https://panoptes-uploads.zooniverse.org/subject_location/ed868913-7c33-44ee-abe7-460d1cb99da7.jpeg
- https://panoptes-uploads.zooniverse.org/subject_location/0cd8af98-3546-47b9-8c65-eb2f8b1fd7c8.jpeg

View it on the Classifier:
https://www.zooniverse.org/projects/abbsta/south-coast-threatened-fauna-recovery-project/classify/workflow/21967/subject/98393286
</details>

Each problem subject belongs to Subject Set 120148. However, other subjects in the same Subject **don't** have any issues (at least based on a random sampling).

<details>
<summary>Example of a working subject in set 120148: subject 98392820</summary>

- https://panoptes-uploads.zooniverse.org/subject_location/d6ded98b-7058-46d6-b99f-8fa41fd1e2ec.jpeg
- https://panoptes-uploads.zooniverse.org/subject_location/ae77a8a2-eae8-4b7e-946a-df6daaea758c.jpeg
- https://panoptes-uploads.zooniverse.org/subject_location/ac0c9980-55e4-4b56-b3e0-aac04598323d.jpeg

View it on the Classifier:
https://www.zooniverse.org/projects/abbsta/south-coast-threatened-fauna-recovery-project/classify/workflow/21967/subject/98392820
</details>

**Comment by shaunanoordin** [comment] 2024-10-10 15:52
The "broken subjects" (subjects with broken image files) seem to have occurred at random. All broken subjects belong to one subject set, but there are other subjects in that set that are perfectly OK. My best guess is that either the upload process went wonky (due to... network shenanigans?), or perhaps those specific image files were already broken at the source.

Next steps?
- (Short term) inform project owners (and volunteers?) of the issue. Remove affected subject set from Workflow (because it's complete anyway. I'd rather not delete the individual broken subjects, as it would be difficult to replicate this exact problem when trying to create a fix.)   
- (Long term) Not sure what the correct behaviour should be when the FEM Classifier encounters a "broken subject". Display an error message, then have a popup that says "go to the next Subject" ?  (What if the next few Subjects are also broken, as in this case?) This requires more discussion - will need to tag in rest of the team. (At minimum, a more descriptive error message might help users.)

**Comment by trouille** [comment] 2024-10-10 17:18
Great. @shaunanoordin Can you post here which subject set(s) are affected? I can then follow up with the research team on unlinking those subject sets (and seeing if they have any insight on what might have corrupted those images). 

Project banner is up to indicate the issue to the volunteers, etc.

**Comment by shaunanoordin** [comment] 2024-10-11 15:11
(echoing from Slack)

Known subjects with broken images: `98392540, 98392819, 98393284, 98393285, 98393286, 98393287`

All those belong to subject set `120148` [(link: Project Builder)](https://www.zooniverse.org/lab/15224/subject-sets/120148)

**Comment by trouille** [comment] 2024-10-11 15:19
My apologies! Missed it in the thread above. Thanks! I'll follow up w/ the team now.

**Comment by goplayoutside3** [comment] 2024-10-14 15:11
Because this was a bug caused by a few specific subjects with broken images, I'm going to close this Issue and echo what Shaun mentioned above:

> (Long term) Not sure what the correct behaviour should be when the FEM Classifier encounters a "broken subject". Display an error message, then have a popup that says "go to the next Subject" ? (What if the next few Subjects are also broken, as in this case?) This requires more discussion - will need to tag in rest of the team. (At minimum, a more descriptive error message might help users.)

If this is a desired feature it should be described in a separate Issue.

**Closed by goplayoutside3** 2024-10-14 15:11 UTC
Labels: bug
